[.text-center]
== MyLibreLab user documentation and tutorials
:author: Foad Sojoodi Farimani
:email: f.s.farimani@gmail.com



== Abstract:

[.text-justify]
MyLibreLab software is visual programing environment, specially to control and communicate with microcontrollers (MCU) and microprocessors. Using blocks, which carry specific functionality, and connections the user can implement an algorithm. The software includes elements to communicate with the commonly used MCU development/expansion boards and single-board computers, such as Arduino&#174;, Raspberry Pi&#174;, and Android&#8482; devices. MyLibreLab can be considered as a Free, Libre, And Open Source Software (FLOSS) alternative to National Instrument&#8482;'s LabVIEW&#8482;. The user can design graphical user interfaces (GUI) to control electronic hardware through serial communication (USB UART).

MyLibreLab is hard fork of the parent project MyOpenLab with the specific goals of reviving the international community, as well as using modern development practices and tools. The MyOpenLab project was initiated by Carmelo Daniel Salafia, a German developer, in 2006. In 2017 the development was handed over to Robinson Javier Velásquez, a Spanish developer.

The MyLibreLab code base has a licence of The GNU General Public License v3.0 which means ... and these documentation is licenced as Creative Commons BY-NC-SA meaning ...

If you have just started learning the software please read the FAQ section first and then follow the Tutorials.

=== Community:
There are several ways you can get in touch with the community. If you have questions you are encouraged to ask them via https://github.com/MyLibreLab/MyLibreLab/issues[GitHub issues] using the tag `[Question]` at the beginning of the title and post the link to the https://discord.gg/dbD8AR7[Discord group]. If you want to stay in touch with the community https://discordapp.com/download[install the Discord app] on your computer or mobile phone. Alternatively you may use the `##MyOpenLab` or `#MyOpenLab` IRC channels on Freenode, post questions on https://myopenlab.org/inicio/comunidad/[MyOpenLab Forum] or https://sourceforge.net/p/myopenlab3/tickets/[its SourcForge issues].

Before asking new questions please consult the internet using search engines (e.g., Google) to be sure it is not asked before. Duplicate questions are not appreciated.

=== Installation:

MyLibreLab is Java program so basically you should be able to download the latest version and run it on all Operating Systems (OS) such as GNU/Linux, macOS, and Windows. But we highly recommend that you use a package manager.

* **Windows:** On Windows OS please use Chocolatey package manager

    choco install mylibrelab

* **macOS:** On macOS Os please use HomeBrew Cask package:

    brew cask install mylibrelab

* **GNU/Linux:** using AppImage...?

=== FAQ:

* **Who is this software for?** MyLibreLab is a software for students, educators, and makers who want to do visual programming and hardware communication (i.e., serial UART).
* **Is it a complete LabVIEW alternative?** Not at all. LabVIEW is an expensive proprietary software designed and maintained by a big group of developers at National Instrument for last couple of decades. MyLibreLab is a community driven project maintained by volunteers. You can not open LabVIEW files in MyLibreLab or vise versa.



== Tutorials:
include::Tutorials/ex001/README.adoc[]
