on:
  push:
    branches:
      - master

jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy images
        shell: bash
        run: |
          mkdir /tmp/out
          find . -name "pics" -exec cp -r {} /tmp/out \;
      - name: Run asciidoctor
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -o /tmp/out/index.html README.adoc"
      - name: Collect for gh-pages
        shell: bash
        run: |
          mv /tmp/out .
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: out
