on:
  push:
    branches:
      - master

jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy images
        shell: bash
        run: |
          mkdir out
          pwd
          ls -la
          ls -la out
          find . -name "pics" -exec cp -r {} out \;
          ls -la out
          find out
      - name: Run asciidoctor
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -o out/index.html README.adoc"
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: out/
